### ISSUE TITLE
open XiEditor from the command line

### ISSUE THREAD

**Issue by cmyr** [google/xi-mac#111]
We'd like this eventually. In the interim, I currently have a teeny bash script at `/usr/local/bin/xi`:

```sh
#! /bin/sh
open -a XiEditor $@
```

This requires XiEditor to be installed somewhere, like /Applications. You can also replace `XiEditor` with a path to the app bundle.

edit: simplified script

**Comment by vlovich** [comment]
Are you saying eventually you want a terminal front-end or just the ability to invoke the Gui from the command-line?  If it's the latter we can just package your script into the .app & on startup check for /usr/local/bin/xi - if missing copy it there.

**Comment by cmyr** [comment]
@vlovich Right, I'm talking about essentially packaging this script; I had the idea that it might make sense to add various options, but that can be future work. I'm not sure how best we would go about installing this; we don't necessarily know the path to the `XiEditor.app` package. There's probably a way to figure this out, I don't really know much about the mac app install process...

**Comment by srigsby** [comment]
perhaps not helpful but here's an alias I've been using:  

    alias xi="open $HOME/xi-mac/build/Release/XiEditor.app"

**Comment by srigsby** [comment]
perhaps off topic or not useful but this is the alias I use for "opening XiEditor from the [cmd] line":  

    alias xi="open -a $HOME/xi-mac/build/Release/XiEditor.app"

**Comment by WillCraig** [comment]
I wanted to make a more detailed set of instructions for idiots like myself (Who took 4 hours to get this to work)
type `open . profile` in the terminal, put this in the .profile file
```
alias **xi** ="open /path/to/xieditor.app"
```
type `source .profile` after saving the text file
 
(*You can change the name of the alias (bolded) to anything you want.

**Comment by vlovich** [comment]
This is typically done on OSX by bundling the script into the .app & then offering an option to deploy it into /usr/local/bin if it's not present.  Would be happy to accept a PR that does this.

**Comment by OberstKrueger** [comment]
Absent a smarter method of finding the location of XiEditor.app, the "/Applications" portion of the script can be left off. By default, "open -a" will search both /Applications and ~/Applications, and while I imagine most people will put it in the root Applications, there might be some who put it in the user Applications folder.

**Comment by jansol** [comment]
There's a menu item for installing the helper script mentioned in the OP now.
