### ISSUE TITLE
empty newlines can screw up gutter line numbers

### ISSUE THREAD

**Issue by cmyr** [google/xi-mac#115]
Entering newlines fails to update the line numbers of subsequent lines.

![screen shot 2018-01-18 at 3 16 35 pm](https://user-images.githubusercontent.com/3330916/35119400-c2991f78-fc62-11e7-8a99-4a61112e69bc.png)

**Comment by cmyr** [comment]
@vlovich just caught up on the irc logs; it makes sense to me that this is related to the auto-indent stuff in syntect; at least, that's why you're seeing two updates. We shouldn't be sending the second update in syntect if there is no previous indentation level; I'll open a separate issue for that.
 Annoyingly I'm also not able to reproduce consistently right now?

**Comment by vlovich** [comment]
So I've tracked it down.  There's some kind of bug with the lineCache.  If I disable it 
```
            //if let assoc = lineCache.get(lineIx)?.assoc {
                //textLine = assoc.textLine
                //textLines.append(assoc.textLine)
            //} else {
```
then the line numbers are fine.  FWIW I see no noticeable performance difference.  I'm not sure I understand yet what lineCache is trying to do.  My guess is that the performance implications are for when you have more complex styles being applied.  I'll look into the problem.  My hunch on how the fix is going to look like is that it's going to be a bit involved moving some things around.  The gutterTL and the textLine cache needs to be split up better.

**Comment by vlovich** [comment]
This hack fixes the issue:
```
@@ -466,6 +466,14 @@ class EditView: NSView, NSTextInputClient, TextPlaneDelegate {
             if let assoc = lineCache.get(lineIx)?.assoc {
                 textLine = assoc.textLine
                 textLines.append(assoc.textLine)
+
+                let gutterText = "\(lineIx + 1)"
+                let gBuilder = TextLineBuilder(gutterText, font: font)
+                gBuilder.setFgColor(argb: line.containsCursor ? foregroundArgb: gutterArgb)
+                let gutterTL = gBuilder.build(fontCache: renderer.fontCache)
+
+                let fixupGutter = LineAssoc(textLine: assoc.textLine, gutterTL: gutterTL);
+                lineCache.setAssoc(lineIx, assoc: fixupGutter);
             } else {
                 let builder = TextLineBuilder(line.text, font: font)
                 builder.setFgColor(argb: foregroundArgb)
```
The less hacky way I'm thinking of doing it is to have 2 LineAssoc.  1 for the text itself and 1 for the gutter.  Then move the rendering of the gutter lower.  Not sure how involved that is or if there's a simpler fix.

**Comment by cmyr** [comment]
Interestingly, this is not an issue if linewrap is enabled (this was my reproduction problem). I don't know too much about that code, but I guess it's sending a different update. It's not immediately clear to me that that should be expected in this case?

**Comment by raphlinus** [comment]
I don't think it's a huge mystery, the current linewrap code overinvalidates, which can mask the underlying problem.

Vitali's approach seems good to me, let's get it merged.
