### ISSUE TITLE
Find UI magnifier icon not shown

### ISSUE THREAD

**Issue by rkusa** [google/xi-mac#120]
The magnifier icon in the Find bar is not shown anymore.

![screen shot 2018-01-26 at 14 50 30](https://user-images.githubusercontent.com/409021/35442662-56799330-02a8-11e8-8550-f990f0a9f421.png)

I was able to track this issue back to the changes in `Main.stroyboard` in dc4840e.

Unfortunately, I have no idea how to fix this. Maybe the `NSSearchField` itself is buggy?

**Comment by rkusa** [comment]
I am more or less just guessing, but could it be due to the `EditView` being a layer-hosting view now? I found the following in the docs about layer-hosting views:

> Similarly, do not add subviews to a layer-hosting view.

But we are adding the `FindViewController`'s view as a subview to `EditView`.

**Comment by cmyr** [comment]
I think you're right. There should be a fairly trivial work-around, which would be to have the find view be a sibling of `EditView`, probably a child of `EditContainerView`?
