### ISSUE TITLE
Very slow performance on big JSON file

### ISSUE THREAD

**Issue by PierBover** [google/xi-mac#127]
As [instructed by cmyr in HN](https://news.ycombinator.com/item?id=16269826) I'm opening this issue about a very slow performance with a large JSON file.

[postal-codes-cloud-function.json.zip](https://github.com/google/xi-mac/files/1682150/postal-codes-cloud-function.json.zip)

I built using `xcodebuild` so not sure if release or debug mode.

The file opens reasonably fast compared to other editors, but moving the cursor, focusing and unfocusing the window, etc, take a very long time and show the mac beach ball. Also the menu on the system bar becomes unresponsive.

I'm on 10.13.3.

**Comment by cmyr** [comment]
Ah I understand. We do currently have some performance issues around really long lines. There's a related issue at #20.

**Comment by PierBover** [comment]
Ok, I guess it's better to close this then.
