### ISSUE TITLE
When opening preferences via `CMD+,`, the entire page doesn't load at first.

### ISSUE THREAD

**Issue by zachdaniel** [google/xi-mac#130]
Just exploring this repo and xi-editor, going to get my feet wet soon. I got it open and figured I'd try out the preferences panel, and this is what happened.

![xi-mac bug](https://user-images.githubusercontent.com/5722339/35703153-2bf0d752-0769-11e8-9824-374d116ea75f.gif)

Only the first few lines are displayed, and then the rest is filled in as I scroll.

If, however, I type into the document and then hit `CMD+,` it opens it in a new frame which works just fine. So this is only when it opts to open it in the existing frame.

**Comment by cmyr** [comment]
Interesting, this was a known issue but I thought it had been resolved. I'll see if I can reproduce.

**Comment by cmyr** [comment]
@zachdaniel I don't imagine there's any chance your xi-mac is a bit behind master? I'm not able to reproduce.

**Comment by zachdaniel** [comment]
Says I'm up to date on master. Perhaps I have outdated tooling?

**Comment by zachdaniel** [comment]
Looks like I was still running on nightly rust. Let me see if switching back to stable helps.

**Comment by cmyr** [comment]
I don't think it should be related; what this looks like is that the front-end isn't sending the "scroll_to" RPC, which indicates the size of the viewport, but I'm not sure why that's happening. One possibility is that `EditViewController.visibleLines` isn't getting reset; we check that before sending the scroll notification to avoid duplicate events. It _should_ be getting reset in `XiDocumentController.openDocument`. If you feel like firing up Xcode, that's at least somewhere to look.

My guess is that we're racing on resetting `visibleLines`, but very much a guess.

**Comment by zachdaniel** [comment]
@cmyr I'll use this issue as an excuse to just dive in and get my hands dirty. All I know about swift I learned when it was announced and I did a tutorial, but I might be able to piece something together :) I mostly came to this project for the rust, but if I pick swift up too, NBD.

**Comment by zachdaniel** [comment]
From what I can see, it's sending visible lines explicitly as `currentDocument.editViewController?.visibleLines = 0..<0`

**Comment by zachdaniel** [comment]
So it looks like we go down a separate path if the current document is empty, where we basically simulate the current document as the new file but freshly opened.
`if let currentDocument = self.currentDocument as? Document, currentDocument.isEmpty`

Is that an accurate assessment?

**Comment by zachdaniel** [comment]
I should probably not clutter up these github issues with "me learning swift"!

**Comment by cmyr** [comment]
@zachdaniel ping me on irc if you want some real-time help with this? cmyr@irc.mozilla.org

**Comment by Garee** [comment]
I also see this issue.

It looks like `EditViewController.willScroll` is not invoked if you open the preferences file from an empty document. 

I added the following and it seems to fix it, but I don't know if it's the correct approach.

```swift
// In EditViewController
func willScrollToOrigin() {
    willScroll(to: scrollView.contentView.bounds.origin)
}

// In XiDocumentController L63-71
Events.NewView(path: url.path).dispatchWithCallback(currentDocument.dispatcher!) { (response) in
    DispatchQueue.main.sync {
        currentDocument.coreViewIdentifier = response
        currentDocument.editViewController?.visibleLines = 0..<0
        currentDocument.editViewController?.willScrollToOrigin() // Here
        currentDocument.fileURL = url
        self.setIdentifier(response, forDocument: currentDocument)
        completionHandler(currentDocument, false, nil)
    }
}
```

I hope this helps.

**Comment by cmyr** [comment]
@Garee I have a patch inbound, but this is very close to my approach. Were you also seeing this issue?

**Comment by cmyr** [comment]
@zachdaniel when you're back around, you can see if this patch fixes this for you? https://github.com/google/xi-mac/pull/131

**Comment by Garee** [comment]
@cmyr I could reproduce the issue and #131 fixes it for me.

**Comment by cmyr** [comment]
@Garee okay cool, I'm going to assume this was some behaviour change between 10.12 (which I'm on) and 10.13 (which I'm assuming you're on); the correct-seeming behaviour on 10.12 was accidental. 😁

**Comment by zachdaniel** [comment]
Fixes for me as well.
