### ISSUE TITLE
Include Inconsolata (font) in the app bundle

### ISSUE THREAD

**Issue by cmyr** [google/xi-mac#134]
This would ensure that everyone had the same experience out of the box, and also has nice evangelism benefits. ~I'm not sure if there are any legal or otherwise concerns, though. @raphlinus?~

In terms of the actual work, bundling the fonts should be trivial; what I'm not sure about is how we actually use them from the app bundle. It's certainly doable though.

**Comment by raphlinus** [comment]
I think this is a good idea. There shouldn't be any legal concerns, the fonts are released under the perfectly cromulent OFL license, which allows bundling in a wide range of contexts.

There is a question of which version is best. InconsolataGo is a possibility, but it also lacks some updates and character set coverage from the latest Google Fonts [version](https://github.com/google/fonts/tree/master/ofl/inconsolata). I've heard reports of rendering artifacts with the latter; these should be investigated.

**Comment by cmyr** [comment]
closed by #153
