### ISSUE TITLE
display lag while modifying selection

### ISSUE THREAD

**Issue by cmyr** [google/xi-mac#15]
Currently, dragging and modifying a selection causes a perceptible display lag. This shouldn't happen. It might be simply that the calculation of deltas when sending updates hasn't been particularly optimized, and we're just invalidating big swathes of the line cache? If not then this is something to improve.

**Comment by cbrewster** [comment]
Is this from after a build with https://github.com/google/xi-mac/commit/838bb31cecb0ca8d23a4208ed36d8fe21a43b233?

**Comment by cmyr** [comment]
yea, there's still a perceptible display lag when dragging. Although after building for release it's much better. Which is definitely the benchmark. But if we're laggy even in debug we're doing something wrong somewhere. 

But there's lots we can do around drawing performance that's been discussed elsewhere, I'll close this.
