### ISSUE TITLE
Find is broken

### ISSUE THREAD

**Issue by cmyr** [google/xi-mac#154]
Since we moved to openGL backed drawing find is broken in a few ways:

- touch handling / focus: clicking away from the find window should change the first responder. In a more general sense, the behaviour around input focus while the find view is visible should be audited, there's probably a bunch of subtle stuff wrong.

- highlights aren't drawn: the `TextLine` has no concept of find highlights. Probably the various span types should be combined into a Spans<T> (there's a comment suggesting as much) and we should allow 'selection' spans to have an arbitrary associated color. Only one of [active find highlight, inactive find highlight, active selection, inactive selection] can exist for a given span at a given time, so I think we only need one field? Don't quote me on that, but I believe it's the case.

**Comment by rkusa** [comment]
For _touch handling / focus_ we should also hide the caret of the document as long as the find view textfield is focused. Currently, when the find view textfield is focused, we basically have to blinking cursors (one in the textfield and one in the document).
