### ISSUE TITLE
Rewrap (F1) can't be undone and doesn't mark a buffer as changed.

### ISSUE THREAD

**Issue by timburks** [google/xi-mac#167]
I noticed that after rewrapping source files (tested with Rust and Swift), the changes can't be undone, and if rewrap was the only change, the containing window can be closed without warning. (Typically an attempt to close a changed file triggers an alert with a warning.) 

Found on a fresh build of master (commit 9af3f596e3122ab54eecd279c323077497cac448).

**Comment by cmyr** [comment]
@timburks thanks for this!

rewrap from the debug menu was very much a testing feature, and should probably be removed, although it may be getting used for real width measurement, which is currently in flight.

If you'd like a more useful version of rewrap, you can set a column width in your preferences file.

**Comment by raphlinus** [comment]
Also it _shouldn't_ mark a buffer as changed, because it only affects the view. Perhaps you're thinking of a feature like "gwap" in vi, which would also be useful.

**Comment by timburks** [comment]
Thanks for your explanations! I don't need the Rewrap feature; I was just poking around and this struck me as a minor surprise worth mentioning. 

It would be more clear that rewrap only affects the view if the line numbers on the left didn't update to reflect the wrapping. Also, rewrap seems to put the view in a wrapping mode that causes new text to be wrapped. I haven't found a way to exit that mode.

**Comment by cmyr** [comment]
@timburks you're correct on both counts. The line numbers should be considered a bug, and there's an open issue in xi-core (https://github.com/google/xi-editor/issues/184) and the 'not being able to exit this mode' is an acceptable consequence of this only existing for testing. For finer-grained playing around you can change your config file. :)
