### ISSUE TITLE
failed to run custom build command for `onig_sys v61.1.0`

### ISSUE THREAD

**Issue by wallywyyoung** [google/xi-mac#17]
macOS 10.12.4
XCode 8.3.1 fresh from AppStore 
Rust 1.16.0 off Homebrew

Ran build commands in README, produced this error:
failed to run custom build command for `onig_sys v61.1.0`

**Comment by cmyr** [comment]
@wallywyyoung you need to run `cargo update` in rust/syntect-plugin` probably.

**Comment by raphlinus** [comment]
Probably you don't have cmake installed? I wish this part were pure Rust...

**Comment by jpcaruana** [comment]
`brew install cmake` solved this issue for me. thanks

**Comment by wallywyyoung** [comment]
D'oh! Cmake was the culprit. Pitfalls of a new machine. Thank you @raphlinus.
