### ISSUE TITLE
Incorrect font size on app launch

### ISSUE THREAD

**Issue by Kirow** [google/xi-mac#170]
When I launch the app I always start with 14pt font size, even when I have different value in settings file. 
So I need to go to the settings and make 2 changes before I can get needed font size.

For example:
- settings font size = 20
- when app launch I see font size 14 instead of 20
 - need to change from 20 to 19 for example, hit save
 - then change from 19 to 20 and save file again

**Comment by cmyr** [comment]
@Kirow What is your "font_face" setting? is it possible that this font is missing, and we're using a fallback font? 

It's possible that there's a mismatch between the font in the default config file and the font that we're actually shipping with xi-mac.

**Comment by Kirow** [comment]
@cmyr I used default settings,  just increased `font_size`
```
font_face = "InconsolataGo"

# In points
font_size = 22
```

then played with `tab_size` param,  just to check that it don't have same problem as `font_size`.

**Comment by cmyr** [comment]
@Kirow Can you change "font_face" to a font you know you have installed? say, "Menlo"?

**Comment by Kirow** [comment]
@cmyr Yes, it works with Menlo correctly. But I think I've read somewhere that `InconsolataGo` was bundled into the app.

**Comment by cmyr** [comment]
@Kirow yea, this is the problem: we actually bundle `Inconsolata`, but the default config file names `InconsolataGo`, which is a variant of the font we were using earlier. Will have to update that. In the meantime if you change `InconsolataGo` to `Inconsolata` in your prefs file things should work as expected.

**Comment by Kirow** [comment]
@cmyr Ok, understood. Thanks

**Comment by cmyr** [comment]
And if you're interested in submitting a fix, this would be a matter of updating this file: https://github.com/google/xi-editor/blob/master/rust/core-lib/assets/client_example.toml

**Comment by cmyr** [comment]
@Kirow okay, no worries! and yes, I agree that font-size should always be used.
