### ISSUE TITLE
Doesn't seem to work on mac. Could not compile `xi-rope`

### ISSUE THREAD

**Issue by kant111** [google/xi-mac#181]
I followed the below instructions
[](
> git clone https://github.com/google/xi-mac
> cd xi-mac
> git clone https://github.com/google/xi-editor
> xcodebuild
> open build/Release/XiEditor.app)

And I get the following Error when I run `xcodebuild`

```
 function that returns `Result` (or another type that implements `std::ops::Try`)
    |                                     in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<usize>`
    = note: required by `std::ops::Try::from_error`

error: aborting due to 16 previous errors

error: Could not compile `xi-rope`.
warning: build failed, waiting for other jobs to finish...
error: build failed

** BUILD FAILED **


The following build commands failed:
	ExternalBuildToolExecution xicore
(1 failure)
```

**Comment by cmyr** [comment]
@kant111 what's the output of running `rustc --version` from a terminal? What happens if you run `cargo build` from `xi-editor/rust`?

**Comment by kant111** [comment]
`rustc --version`
rustc 1.21.0 (3b72af97e 2017-10-09)

cargo build from xi-editor/rust

[error[E0277]: the trait bound `str: std::marker::Sized` is not satisfied
   --> rope/src/rope.rs:710:37
    |
710 |                 let (pl, poffset) = self.prev_leaf()?;
    |                                     ^^^^^^^^^^^^^^^^^ `str` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `str`
    = note: only the last element of a tuple may have a dynamically sized type

error[E0277]: the trait bound `std::option::Option<(&std::string::String, usize)>: std::ops::Try` is not satisfied
   --> rope/src/rope.rs:714:37
    |
714 |                 let (pl, poffset) = self.prev_leaf()?;
    |                                     -----------------
    |                                     |
    |                                     the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                                     in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<(&std::string::String, usize)>`
    = note: required by `std::ops::Try::into_result`

error[E0277]: the trait bound `std::option::Option<usize>: std::ops::Try` is not satisfied
   --> rope/src/rope.rs:714:37
    |
714 |                 let (pl, poffset) = self.prev_leaf()?;
    |                                     -----------------
    |                                     |
    |                                     the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                                     in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<usize>`
    = note: required by `std::ops::Try::from_error`

error: aborting due to 16 previous errors

error: Could not compile `xi-rope`.
warning: build failed, waiting for other jobs to finish...
error: build failed
](url)

**Comment by kant111** [comment]
upgraded rust to `rustc 1.26.0 (a77568041 2018-05-07)` and Xcode to 9.X as stated in the instructions and it works. Sorry.
