### ISSUE TITLE
find bar looks out of place when unified_toolbar = true

### ISSUE THREAD

**Issue by cmyr** [google/xi-mac#194]
We should probably be styling the find bar as well, in this case, or else we look like this:

![screen shot 2018-06-06 at 7 44 33 pm](https://user-images.githubusercontent.com/3330916/41070670-16ec1dce-69c2-11e8-9a72-b8af1bdfb0e7.png)
![screen shot 2018-06-06 at 7 44 40 pm](https://user-images.githubusercontent.com/3330916/41070672-194e0f50-69c2-11e8-9122-f3fd186c5312.png)

**Comment by jansol** [comment]
Looks like it's broken again, now the find bar appears to be transparent...

**Comment by jansol** [comment]
And fixed again in 8901cdc818f9dda498a98a4b0817322bcfb8267f
