### ISSUE TITLE
Soft wrap to window width?

### ISSUE THREAD

**Issue by nicpottier** [google/xi-mac#199]
Big fan of the project goals and really impressed with the quality of things already!

One question, I see settings to do soft wraps at a set number of characters, but that feels a bit unnatural in OS X when you resize the window to something larger. Is this by design or some setting I'm not seeing?

**Comment by cmyr** [comment]
@nicpottier you need to set `word_wrap = true` in your preferences. (This was merged about an hour ago in #187, so you may need to pull and rebuild)

**Comment by nicpottier** [comment]
Oooh, shiny! Just grabbed both and rebuilt and now I'm getting a beachball though. :( Any logs I can provide to help? (where would they be?)

**Comment by cmyr** [comment]
mmmmm try launching from within xcode? a bunch of changes landed today so I wouldn't be surprised if something is broken.

**Comment by nicpottier** [comment]
Hrmm.. tracked it down to actually me having a buffer open that then crashes when word wrapping is off. I'll see if I can repro it within XCode and open a new issue. (it seems to be present on that file both in the previous version and this new one, so unrelated I think)

Did get this soft wrapping working though, thanks!
