### ISSUE TITLE
Support theming

### ISSUE THREAD

**Issue by cmyr** [google/xi-mac#2]
xi-mac should be themeable. In the simplest case, this should involve support for the themes provided by [syntect](https://github.com/trishume/syntect), and ultimately it should also provide a UI for loading, editing, and saving new textmate / sublimetext theme files.

**Comment by jansol** [comment]
Total gimmick, but a feature I've come to like a lot in iTerm2 is the possibility to set a slightly blurred, semitransparent background. Having this supported in themes would be awesome. (I like seeing my wallpaper through whatever I'm working on)

**Comment by cmyr** [comment]
Conceptually, I think that window opacity is probably the sort of thing that a particular client might choose to implement, but I'm not sure about including it in core. I would also personally not be inclined to include it in xi-mac, but that's just me. ;)

I'm going to close this; basic theme support is working as of #51.
