### ISSUE TITLE
Crash when killing second line repeatedly

### ISSUE THREAD

**Issue by nicpottier** [google/xi-mac#201]
Repro:
 * open blank file
 * write text on first line
 * write text in next line, with cursor at end of line
 * ctrl-a to go to start of line, then ctrl-k repeatedly.

Expected:
 * line deleted, extra ctrl-k's no-noops

Actual:
 * crash

Note doesn't seem to repro on the first line.

**Comment by cmyr** [comment]
I'm guessing this is only a problem when word wrap is on? Looks like this is probably https://github.com/google/xi-editor/issues/625, we might've been a bit premature getting this in. 😕

**Comment by raphlinus** [comment]
Hopefully google/xi-editor#648 (just merged) fixes this. Give it a try.

**Comment by nicpottier** [comment]
👍 yep that fixes it!
