### ISSUE TITLE
Cannot copy text from xi-editor

### ISSUE THREAD

**Issue by singularitti** [google/xi-mac#204]
With current build of xi-editor, I cannot copy text from it on macOS 10.13.5. The clipboard is not updated after I select and copy text in xi-editor.
I use Xcode 9.4 to build, and my `rustc` version is `1.26.2 (594fb253c 2018-06-01)`.

**Comment by cmyr** [comment]
This is possibly related to #196. I'll take a look.

**Comment by cmyr** [comment]
Indeed, wasn't handling this case correctly. Thank you @singularitti! 🙇
