### ISSUE TITLE
Build script broken by cargo workspace

### ISSUE THREAD

**Issue by lord** [google/xi-mac#215]
As described in the comments of #213, looks like the `build-rust-xcode.sh` script is looking for the binary in the `xi-editor/rust/syntect-plugin/target`, but since there's [now a Cargo workspace](https://github.com/google/xi-editor/pull/730) in the `xi-editor/rust/Cargo.toml`, the `target` folder is now at `xi-editor/rust/target`.

**Comment by cmyr** [comment]
I'm having trouble reproducing this; doing a clean build on master/master (xi-mac ea87386 and xi-editor 5b9d874) I don't have any errors? 😕

**Comment by Deltafire** [comment]
I've just tried building this for the first time and run into the same error:

```
   Compiling xi-syntect-plugin v0.0.0 (file:///Users/chris/xi-mac.git/xi-editor/rust/syntect-plugin)
    Finished release [optimized] target(s) in 117.71 secs
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: target/x86_64-apple-darwin/release/xi-syntect-plugin (No such file or directory)

** BUILD FAILED **


The following build commands failed:
	ExternalBuildToolExecution xicore
```
