### ISSUE TITLE
xi-mac crash

### ISSUE THREAD

**Issue by daleione** [google/xi-mac#217]
mac high sierra 10.13.4

- xi-mac version 8e6f47f303b24ac965e1594a4e261e2bfbd7183
- xi-editor version 83ba52a28479f6ad0256641995974c3194eeae8b

both is the lastest version.
rustc 1.27.0 (3eda71b00 2018-06-19)

![image](https://user-images.githubusercontent.com/4003971/42485928-5425600e-842c-11e8-9025-aa7e62aa5529.png)

**Comment by cmyr** [comment]
Okay, thanks, I see the problem, will get a fix up in a sec.

In the future, if you could copy the text of the crashlog that would  be easier than a screenshot, but thanks for the report!
