### ISSUE TITLE
Replace buttons misaligned

### ISSUE THREAD

**Issue by cmyr** [google/xi-mac#219]
I merged all of the replace work this morning, and then when I rebuilt master/master I noticed that the replace buttons are back to being misaligned with the find buttons. Not sure exactly what was up, maybe there was a rebase or something that I missed which screwed up the storyboard? In any case, would be nice to get this fixed again.

Also: we have working find and replace! This is very exciting, great work @scholtzan 😎

**Comment by cmyr** [comment]
Hmm, on another computer and now I think this might be related to either Xcode version or macOS version? I saw it when building with 9.2 on 10.12.x, but not on 9.4 / 10.13.x. 😕

**Comment by scholtzan** [comment]
I saw that the `fillEqually` option is only supported on 10.13+ (https://developer.apple.com/documentation/appkit/nssegmentedcontrol/distribution/fillequally). Maybe it has something to do with that.

**Comment by cmyr** [comment]
Yep that's probably it. I think this is fine, being misaligned on 10.12 is not a big deal, 10.14 will be out shortly.
