### ISSUE TITLE
Enhancement request on Find and Replace

### ISSUE THREAD

**Issue by singularitti** [google/xi-mac#224]
Glad to see xi-mac has implemented basic Find and Replace functionality! The general experience is good, but I still think there could be an enhancement.

That is, when I press cmd+F or option+cmd+F, I find that the Find&Replace bar covers the first and second line text as shown below:
1. original view
<img width="863" alt="original view" src="https://user-images.githubusercontent.com/25192197/42719325-b3dfebec-86e1-11e8-8227-c7d3a3b87f0e.png">
2. after open Find bar
<img width="863" alt="after open Find" src="https://user-images.githubusercontent.com/25192197/42719328-c84315fa-86e1-11e8-9564-7874c47d6c8a.png">
3. after open Find&Replace bar
<img width="863" alt="after open Find&Replace bar" src="https://user-images.githubusercontent.com/25192197/42719391-c1c01d80-86e2-11e8-9dc3-4a83013ecb85.png">

Even I can scroll down two lines to view the 1st and 2nd lines, I still think that the text should scroll down automatically 1 or 2 lines when I am searching or replacing, since this is implemented in other macOS apps like TextEdit.app and Terminal.app:
1. original view
<img width="752" alt="original view" src="https://user-images.githubusercontent.com/25192197/42719360-52ba71a6-86e2-11e8-9f0c-f8aa634c6f13.png">
2. after open Find&Replace bar
<img width="752" alt="image" src="https://user-images.githubusercontent.com/25192197/42719365-60145bdc-86e2-11e8-94ce-5a140ff4f326.png">

1. original view
<img width="752" alt="original view" src="https://user-images.githubusercontent.com/25192197/42719373-741a26de-86e2-11e8-9b52-2320ec16ddd8.png">
2. after open Find bar
<img width="752" alt="after open Find bar" src="https://user-images.githubusercontent.com/25192197/42719378-86d11710-86e2-11e8-9736-4a1351d6fd3c.png">

I would be grateful if you can make this improvement to xi-mac!

**Comment by cmyr** [comment]
Ah I had a response last night but I guess I didn't send it.

1. I definitely agree with this behaviour when the text view is scrolled 'to the top'; that is, if the y origin is visible, I think that the find/replace view should shift the text down, keeping it all visible.

2. I'm less clear about what the behaviour should be when the text view is not scrolled 'to the top'. _Some_ text is going to disappear when we show the find/replace view; it's a matter of whether this text should be at the top or the bottom. The problem with doing it at the bottom (that is, keeping the same visible y origin) is that this means the text view always moves up and down as the find/replace view is shown and hidden. The advantage is that it's consistent, and probably slightly simpler code-wise.

TextEdit:

![2018-07-14 11 17 42](https://user-images.githubusercontent.com/3330916/42725784-94acd71e-8757-11e8-9955-8f81b8825536.gif)

Xi:

![2018-07-14 11 16 44](https://user-images.githubusercontent.com/3330916/42725785-9e889458-8757-11e8-974a-3afea4bd644d.gif)

**Comment by singularitti** [comment]
> I'm less clear about what the behaviour should be when the text view is not scrolled 'to the top'. Some text is going to disappear when we show the find/replace view; it's a matter of whether this text should be at the top or the bottom. The problem with doing it at the bottom (that is, keeping the same visible y origin) is that this means the text view always moves up and down as the find/replace view is shown and hidden. The advantage is that it's consistent, and probably slightly simpler code-wise.

@cmyr I agree your last point, I think we could mimic the behavior of TextEdit.app, which is shown in your screenshot.

**Comment by cmyr** [comment]
I guess my point is that when the find view is visible, there is less screen space available for text. _Some_ text is going to have to be hidden, and it's really a matter of whether we hide that text at the top (covering it with the find view) or if we hide it at the bottom, by pushing it off screen.

**Comment by singularitti** [comment]
Yes, I kind of understand your comment. Well, for me, I prefer pushing the text off screen, if I want to see the pushed-off text, I could press `ESC` to cancel the view. A less consistent behavior (cover the text) is more annoying to me.

**Comment by jansol** [comment]
I also favour pushing text down, since in a text editor text is generally read top-to-bottom so keeping the topmost line constant makes it easier to re-orientate oneself. Contrast with most IM clients, where the initial focus tends to be at the bottom, because more recent messages tend to be much more relevant.

A hybrid approach could also work: push text down *unless* that would obscure the line containing the cursor, in which case obscure the top instead. Maybe add a % of the view height in margins i.e. ensure the cursor and at least N lines of context after it stay visible. Or choose the direction based on which half of the view the cursor is in.

**Comment by singularitti** [comment]
@jansol That's a good idea. I observed that TextEdit.app's behavior is that when user triggers Find&Replace, the cursor just jumps to Find&Replace bar and the text is pushed down, when `ESC` is pressed then everything recovers. I think it is a good hint since user is expected to type inside Find&Replace bar immediately rather than still focus on the cursor.
