### ISSUE TITLE
Memory leak when windows are closed

### ISSUE THREAD

**Issue by ryanbloom** [google/xi-mac#231]
Xi's memory usage increases whenever a file is opened, but doesn't decrease substantially when files are closed. In the Xcode memory debugger, it looks like a reference cycle is keeping old `EditViewController`s in memory.

Here's the closest thing I've found to a fix (see [this branch](https://github.com/ryanbloom/xi-mac/commit/cd18ff80c83dacf58a5ad76ebc569b478488f46f)):

1. Make `EditView.dataSource` weak
2. Make `XiClipView.delegate` weak
3. Make `Document.editViewController` weak
4. Comment out the line where `EditViewController` tells `FindViewController` to update its background color

Unfortunately, this undoes #223 and also introduces a new crash:

`XiEditor(37590,0x1010f1380) malloc: *** error for object 0x6080000e5880: Invalid pointer dequeued from free list
*** set a breakpoint in malloc_error_break to debug
`

The crash has happened opening windows, closing windows, and editing text. The only constant factor seems to be that `malloc` is being called. If I change `XiClipView.delegate` back to strong, the problem goes away.

So I guess it'll take some more work, but I'm not sure what to do about the crash, or why change 4 was necessary.

**Comment by jansol** [comment]
#235 seems to fix all of the points raised here.
