### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by golddranks** [google/xi-mac#244]
With the newest master (both xi-editor and xi-mac):

```
/Users/um003415/repos/xi-mac/XiEditor/XiTextPlane/TextLine.swift:189:48: error: cannot convert value of type 'C.IndexDistance' to expected argument type 'Int'
        newGlyphs.reserveCapacity(glyphIndices.count)
                                  ~~~~~~~~~~~~~^~~~~
                                  Int(              )

** BUILD FAILED **
```

I'm know virtually no Swift so I'm having hard time to decipher what the problem is.

Btw. my `swiftc --version` says:
```
Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
Target: x86_64-apple-macosx10.9
```

**Comment by lukakerr** [comment]
In Swift 4.1 there were [some changes](https://github.com/apple/swift-evolution/blob/master/proposals/0191-eliminate-indexdistance.md) to `C.IndexDistance` (or `Collection.IndexDistance`). Try updating your swift version, i'm on 4.2, but 4.1.3 should be good enough to fix it

**Comment by cmyr** [comment]
This is annoying because afaik Swift 4.0 is the latest you can run on 10.12.x, so this error will be there for anyone running that.

I'd happily accept a patch that adds back the `Int(..)`, which will work across more versions of swift.

**Comment by golddranks** [comment]
Uh oh, I'm stuck on macOS 10.12.6 Sierra because of company policies. That means that I can't install XCode 9.4 that supports Swift 4.1.

I guess I'll be sending a patch.

**Comment by golddranks** [comment]
Oops, that was already fixed in https://github.com/google/xi-mac/commit/445274a504d2f4a44f94a1a0327d53899b01cfc8 ! Thanks! Confirmed to work now so I'm closing this.
