### ISSUE TITLE
thread 'main' panicked

### ISSUE THREAD

**Issue by coin723** [google/xi-mac#248]
I had built XiEditor from this repository and used it well.

However, I can't run/open the app which is built with latest code here.

Here's the log:
>thread 'main' panicked at 'Unable to open log file for xi-core: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', libcore/result.rs:945:5
note: Run with 'RUST_BACKTRACE=1' for a backtrace.

And this is the log of the case of a backtrace:

> thread 'main' panicked at 'Unable to open log file for xi-core: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: xi_core::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start_internal
  14: main

**Comment by cmyr** [comment]
Interesting. @betterclever maybe related to fern changes? Haven't tried to reproduce yet.

**Comment by cmyr** [comment]
@coin723 does https://github.com/google/xi-editor/pull/783 fix this for you?

**Comment by coin723** [comment]
@cmyr Building with that fix solved the problem. Thank you!
