### ISSUE TITLE
Double call of close()

### ISSUE THREAD

**Issue by raphlinus** [google/xi-mac#25]
Repro steps: open new editor, type "abc", ⌘-Q to quit, say "don't save".

```
thread 'main' panicked at 'missing buffer id when closing view', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/option.rs:715
```

Doing a little debugging, it looks like the close() method in Document.swift is being called twice. I don't know whether this is expected behavior (in which it should null out some of its own state on the first call and skip the second), or whether the NSDocument lifecycle is doing something dodgy to make this double call happen.

Should be an easy issue for someone who understands Cocoa.

**Comment by cmyr** [comment]
Yea this wasn't super heavily tested, and we're doing some weird stuff with NSDocument. I'll take a look in the next couple days if nobody beats me to it.
