### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by daubaris** [google/xi-mac#36]
Got this error message while trying to build xi-mac:
```
The following build commands failed:
	     ExternalBuildToolExecution xicore
    (1 failure)
```

**Comment by cmyr** [comment]
1. Is your rustc installed via homebrew? (if yes, try installing via [rustup](https://www.rustup.rs))
2. can you build xi-core itself? (run `cargo build` from `xi-mac/xi-editor/rust/core-lib`).

**Comment by daubaris** [comment]
Rustc wasnt working when installed via `curl https://sh.rustup.rs -sSf | sh` on mac, so I downloaded it with `curl -sf -L https://static.rust-lang.org/rustup.sh | sh` and everything worked as I expected. Thanks.

**Comment by olegskl** [comment]
I have the same problem. Rust is installed with rustup. I'm able to build xi-core.

**Comment by olegskl** [comment]
I had to comment out `set -e` from build-rust-xcode.sh to make it work.
