### ISSUE TITLE
Spamming cmd+z and cmd+shift+z only shows on release

### ISSUE THREAD

**Issue by trishume** [google/xi-mac#44]
### Steps to reproduce
- Set key repeat rate to maximum in System Preferences
- Do a bunch of separate edits in a document (I do this by `a,left,a,left,...`)
- Hold down `cmd+z`, notice "Edit" menu flashing quickly but not all edits immediately dissapearing
- Release `cmd+z`, notice all undos immediately take effect
- Do same for `cmd+shift+z`, notice re-do doesn't take effect until release

This seems like it might be some Cocoa event loop thing? Spamming it manually by tapping as fast as I can works fine, it's only when I use my high key repeat rate to spam it that it gets stuck.

**Comment by rkusa** [comment]
Same when moving back and forth between search results by keeping `cmd+g` or `cmd+shift+g` pressed (in my xi-mac branch for google/xi-editor#286)

**Comment by jansol** [comment]
Appears to be fixed now, so this issue can presumably be closed?
