### ISSUE TITLE
error: failed to run `rustc` to learn about target-specific information

### ISSUE THREAD

**Issue by visualex** [google/xi-mac#45]
Hi! 
This is the tail of my output: 

error: failed to run `rustc` to learn about target-specific information
** BUILD FAILED **
The following build commands failed:
	ExternalBuildToolExecution xicore

**Comment by trishume** [comment]
Do you have the Rust compiler installed? This looks like it can't find the Rust compiler.

**Comment by visualex** [comment]
i do (rustc 1.13.0 (2c6933acc 2016-11-07))
i tried to "cargo build" the backend and got the same:
error: failed to run `rustc` to learn about target-specific information
error: unknown crate type: `proc-macro`

**Comment by cmyr** [comment]
@visualex I think we require rust 1.17 or higher. We also recommend installing via [rustup](rustup.rs), instead of homebrew.

**Comment by visualex** [comment]
@cmyr thanks, installing from rustup worked!!
