### ISSUE TITLE
[Feature Request] Word deletion (alt+backspace, alt+delete)

### ISSUE THREAD

**Issue by jansol** [google/xi-mac#54]
In TextEdit, option(+fn)+backspace deletes a word starting from the cursor position. Seeing as moving the cursor left/right and selecting by word is supported, I'd expect deletion to work the same way.

**Comment by cmyr** [comment]
@jansol would you like to open this issue in the [xi-editor](https://github.com/google/xi-editor/) repo? These commands are actually implemented in xi-mac, they just aren't currently handled by the core. If you look at the Xcode console you'll see an error message for this and for alt+delete, saying that `delete_word_forward` and `delete_word_backward` aren't being handled.

**Comment by jansol** [comment]
Done. Looks like that is indeed the case.
