### ISSUE TITLE
Investigating on markdown rendering issues

### ISSUE THREAD

**Issue by mrandri19** [google/xi-mac#57]
Hi, I'm trying to debug some issues in `xi-gtk`'s markdown syntax highlighting and I'd like to compare it to `xi-mac`'s.
Can I have a screenshot of [this](https://raw.githubusercontent.com/trishume/syntect/master/Readme.md) document please?
Right now it looks like this in `xi-gtk`:
![image](https://user-images.githubusercontent.com/8144521/29319815-8bf658e4-81d5-11e7-83b6-7532e1ede9bf.png)
There are some issues at line `52` because there is a list and backticks. I believe the document should look like [this](https://camo.githubusercontent.com/b5d169adf619d751d8ddfb421910bda6e5818edd/687474703a2f2f692e696d6775722e636f6d2f6137553172326a2e706e67)
Thanks

**Comment by cmyr** [comment]
Here you go. ![screen shot 2017-08-15 at 11 14 31 am](https://user-images.githubusercontent.com/3330916/29322274-f1ef9910-81aa-11e7-8cbb-11d0a1e27915.png)

I would check out syntect's syncat executable, and see what things look like there. It's very possible we have a bug in here somewhere though..

**Comment by mrandri19** [comment]
Yep it's our fault
![image](https://user-images.githubusercontent.com/8144521/29323938-c9d49d3a-81e2-11e7-8630-8c179097639e.png)
Any tips on where I should start to look in xi's source?

**Comment by cmyr** [comment]
@mrandri19 there's an issue open that may be related: https://github.com/google/xi-editor/issues/352

how styles are handled changed recently. There's a tracking issue here with links to some of the discussion, which talks about the change that was made: https://github.com/google/xi-editor/issues/319

There are two places I would look for this bug: the first is in the syntect plugin itself, and the second is in xi-core where we apply the styles from syntect; you could start in `editor.rs`, `plugin_update_spans`.

**Comment by cmyr** [comment]
@mrandri19 I just pushed a change to xi-editor that fixes https://github.com/google/xi-editor/issues/352. Can you check and see if this resolves your problem?

**Comment by jinfagang** [comment]
How to make it support markdown anyway, the default xi seems not open this feature.

**Comment by jinfagang** [comment]
Oh, I have to save as md. Got it.

**Comment by jinfagang** [comment]
How to change the default size of window? Every time it shows in a small window and I have to resize it. If it can remember the last size could be better.

**Comment by raphlinus** [comment]
@jinfagang The window size is a result of changes in #105. That was supposed to use reasonable heuristics but perhaps it's not working well for you for some reason; maybe you want to take a look at the code and possibly experiment with some of the constants?

**Comment by jinfagang** [comment]
@raphlinus Thank your pal. I just mention everytime open it should do a redundant resize action is waste of time. May be other people more like a clean way. So keep it is.

**Comment by cmyr** [comment]
@jinfagang The default size of the window is currently the size of the last window you moved or resized, the previous time you used the editor.

Maybe you're right, and a better behaviour would be to use the size of the currently active window, if there is one?

Also there should probably be a menu for selecting syntax without saving the file. How we handle 'syntax' at the moment is a bit confused. 😕 

Anyway, thanks for sharing your observations, it's very helpful.
