### ISSUE TITLE
Build does not work with zsh-only features in zshrc

### ISSUE THREAD

**Issue by belak** [google/xi-mac#58]
Because bash is specified at the top of `build-rust-xcode.sh`, any time a user has something not supported by bash in their zshrc, the script will error and the build will hang. Below is some sample output while using my [zshrc](https://github.com/belak/dotfiles/blob/master/zshrc).

```
    export variant=normal
    /bin/bash /Users/k.elwert/Code/xi-mac/build-rust-xcode.sh
/Users/k.elwert/.zshrc: line 4: typeset: -U: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
/Users/k.elwert/.zshrc: line 13: zstyle: command not found
/Users/k.elwert/.zshrc: line 14: zstyle: command not found
/Users/k.elwert/.zshrc: line 15: zstyle: command not found
/Users/k.elwert/.zshrc: line 16: zstyle: command not found
/Users/k.elwert/.zshrc: line 17: zstyle: command not found
/Users/k.elwert/.zshrc: line 18: zstyle: command not found
/Users/k.elwert/.zshrc: line 19: zstyle: command not found
/Users/k.elwert/.zshrc: line 20: zstyle: command not found
/Users/k.elwert/.zshrc: line 21: zstyle: command not found
/Users/k.elwert/.antigen/antigen.zsh: line 2: /bin/antigen.zsh: No such file or directory
/Users/k.elwert/.zshrc: line 40: antigen: command not found
/Users/k.elwert/.zshrc: line 43: antigen: command not found
/Users/k.elwert/.zshrc: line 44: antigen: command not found
/Users/k.elwert/.zshrc: line 45: antigen: command not found
/Users/k.elwert/.zshrc: line 47: antigen: command not found
/Users/k.elwert/.zshrc: line 50: unsetopt: command not found
/Users/k.elwert/.zshrc: line 55: chruby_auto: command not found
^C** BUILD INTERRUPTED **
```

I believe this was caused by #56. Although it may fall victim to the same pitfalls, using something like `~/.zshenv` or `~/.zprofile` would be a little less risky.

**Comment by cmyr** [comment]
@belak okay noted, I wasn't sure what the best approach to this was. (I'm still not). All we're really interested in is making sure cargo is in our path, I think. I'm not sure what the elegant solution is.. 😒

**Comment by belak** [comment]
Potentially you could check if cargo is on the PATH and if it isn't, there would be a config file somewhere which would specify the location.

**Comment by jansol** [comment]
How about checking if CARGO_HOME is set and if it isn't ask the user to set it before building? Potentially with a .env file.

**Comment by belak** [comment]
Yeah, I think that might be a good option.

**Comment by cmyr** [comment]
@belak @jansol let me know if this looks like an improvement: https://github.com/google/xi-mac/pull/61

**Comment by mitchhentges** [comment]
Hey, maybe you don't need to `source` either `bash_profile` or `zshrc`. Whatever shell the user is using, if its `rc` file adds `cargo` to the path (or sets `CARGO_HOME`), then `build-rust-xcode.sh` has all the information it needs. If the necessary variables _aren't_ set, then sourcing the `rc` file _again_ (`bash_profile` or `zshrc`) won't have an effect, right?

I can make a PR to remove the `source` lines, if that makes sense.

**Comment by belak** [comment]
@mitchhentges Unfortunately, if you're building directly from xcode, you won't have the environment variables in that instance. The PR cmyr mentioned looks like the best option at the moment.
