### ISSUE TITLE
Build fails with Xcode 8.3.3 (build version 8E3004b)

### ISSUE THREAD

**Issue by rjammala** [google/xi-mac#73]
I am using nightly Rust and here is my version of Swift:

swift --version
Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
Target: x86_64-apple-macosx10.9

   Compiling xi-plugin-lib v0.1.0 (file:///Users/rajanikanth.j/xi-mac/xi-editor/rust/plugin-lib)
warning: unused `std::result::Result` which must be used
   --> /Users/rajanikanth.j/xi-mac/xi-editor/rust/plugin-lib/src/state_cache.rs:116:5
    |
116 |     plugin_base::mainloop(&mut my_handler);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(unused_must_use)] on by default

   Compiling xi-syntect-plugin v0.0.0 (file:///Users/rajanikanth.j/xi-mac/xi-editor/rust/syntect-plugin)
    Finished release [optimized] target(s) in 70.4 secs

=== BUILD TARGET XiEditor OF PROJECT XiEditor WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

**Comment by cmyr** [comment]
We've migrated to Swift 4.0, which requires Xcode 9.0 or greater. Thanks for the issue, I'll update the readme.
