### ISSUE TITLE
Could not compile `xi-core-lib` - config_files.for_each

### ISSUE THREAD

**Issue by vietlq** [google/xi-mac#76]
I got an error when building xi-mac. My Rust: `rustup 1.7.0 (813f7b7a8 2017-10-30)`

```
   Compiling xi-core-lib v0.2.0 (file:///Users/vietlq/projects/xi-mac/xi-editor/rust/core-lib)
error: use of unstable library feature 'iterator_for_each' (see issue #42986)
   --> core-lib/src/tabs.rs:680:22
    |
680 |         config_files.for_each(|p| self.load_file_based_config(&p));
    |                      ^^^^^^^^

error: aborting due to previous error

error: Could not compile `xi-core-lib`.

To learn more, run the command again with --verbose.

** BUILD FAILED **


The following build commands failed:
	ExternalBuildToolExecution xicore
(1 failure)
```

**Comment by raphlinus** [comment]
Not sure exactly what's going on here. I just tried building master using Rust 1.21 and it works, but the linked issue suggests that the "iterator_for_each" feature lands in 1.22.

What's the `rustc --version` output for you? If you do `rustup update` does it fix it?

Possibly we need to do a doc update bumping the rust version.

**Comment by cmyr** [comment]
Yea readme currently says rust 1.20 +. Maybe it should just say "latest stable rust"?
