### ISSUE TITLE
Font menu missing

### ISSUE THREAD

**Issue by jameshiew** [google/xi-mac#78]
From [README.md](https://github.com/google/xi-mac/blob/master/README.md)
> It will look better if you have InconsolataGo installed, a customized version of Inconsolata tuned for code editing. You can change fonts per window in the Font menu or with Cmd-Shift-T. To choose another default font, edit the CTFontCreateWithName() call in EditView.swift.

I followed the command line build instructions but don't have a Font menu in the menu bar, Cmd-Shift-T doesn't seem to do anything.

![screen shot 2017-11-21 at 16 12 48](https://user-images.githubusercontent.com/2990876/33083359-180bb07e-ced7-11e7-9502-fc8ed3cfced5.png)

**Comment by cmyr** [comment]
Yes! it was removed in the latest build to make way for file-based configuration, but we haven't added documentation yet. That should come in the next day or so. Will also update the readme.

Temporarily, you can specify the font by creating a file called `preferences.xiconfig` in `~/.config/xi/`, with the following (optional) keys (and your preferred values):

```toml
font_face = "InconsolataGo"
font_size = 14.0
translate_tabs_to_spaces = true
tab_size = 4
```

thanks for the issue, will get this fixed this evening i hope. 😎
