### ISSUE TITLE
Screen flickers when open a file in new tab

### ISSUE THREAD

**Issue by lennylxx** [google/xi-mac#79]
Repro steps:

1. Open XiEditor, there will be an open file named `Untitled`.
2. <kbd>Command</kbd>+<kbd>O</kbd> to open a file.
3. Click around (or use arrow key) to move the cursor in the edit window.

Or reproduced by:
1. Open XiEditor, there will be an open file named `Untitled`.
2. <kbd>Command</kbd>+<kbd>W</kbd>  or click the close button to close this window.
3. <kbd>Command</kbd>+<kbd>O</kbd>  to open a file named `a.txt`, this will be in a new window.
4. <kbd>Command</kbd>+<kbd>T</kbd>  to open a new tab in this window.
5. <kbd>Command</kbd>+<kbd>O</kbd>  to open another file named `b.txt`.
6. Click around (or use arrow key) to move the cursor in the edit window.

Actual result:
Looks like the window is refreshing and there is flash/flickering every time you move the cursor.

Expected result:
No flash/flickering

**Comment by raphlinus** [comment]
A looked into this a little, and found that repro was inconsistent (it was particularly hard to repro when I was looking closely). Also, a quick scan of the code shows that it's trying to do the right thing - if the RPC isn't set up, the scroll request goes into a pending queue. So there's something deeper going on here.

**Comment by cmyr** [comment]
Just realized what the bug is, here while working on something related:

When we open in an existing tab, the logic that does the initial line fetch doesn't happen because it is called from the view's `viewDidAppear`, which happens when we first open the tab but before we open the file.

Not sure what the best solution is, but should be trivial.

**Comment by cmyr** [comment]
@lennylxx Would you like to check and see if you can still reproduce this on master? I _believe_ it's fixed, but I had trouble reproducing consistently.

**Comment by lennylxx** [comment]
@cmyr Build on top of 4603667e01796237bcae46a21edde2366cf8cd0a and https://github.com/google/xi-editor/commit/53f4267c75da28a80708a531e7ae76071ccfcb41, it can't be reproduced.
I think it's fixed. Thank you for the work!

**Comment by cmyr** [comment]
@lennylxx great, thanks for the follow-up!
